"""
main_roundabout.py
==================
Single-car roundabout scenario using:

  1. **Frenet-frame lanelet map**  (``roundabout_lanelets.py``)
     Decoupled longitudinal (s) and lateral (d) coordinate axes.

  2. **DFATree-based DP**  (``dfa_tree_r1_risk_min.py``)
     Risk-minimising decoupled value iteration wrapped in a DFA tree
     structure that prepares the system for multi-agent / LTL specs.
     Cost design:
       - road cells have *negative* cost → reward for driving
       - lane edges have *positive* cost → risk penalty
       - higher forward speed gets a lower (more negative) action cost
     ⟹ The car naturally drives forward and stays centred.

  3. **MPC tracking controller**  (``trackingMPC.py``)
     Tracks a Cartesian reference trajectory generated by rolling out
     the DP policy in Frenet and converting each waypoint.

Architecture
------------
    ┌──────────────┐     ┌──────────────────┐     ┌──────────────┐
    │  Roundabout   │────▶│  DFATree DP       │────▶│  MPC Tracker │
    │  Lanelet Map  │     │  (decoupled s, d)  │     │  (CARLA)     │
    └──────────────┘     └──────────────────┘     └──────────────┘
          ▲                        │
          │    Frenet (s,d)       │  (v_s, v_d) actions
          └────────────────────────┘

Multi-agent behaviour will be added later.
"""

import argparse
import time
import math

import numpy as np
import sys
import os

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
script_dir = os.path.dirname(os.path.abspath(__file__))

# Add multi_agent_emergency/ itself so that top-level packages
# (abstraction/, scenarios/, control/, perception/, …) are importable
if script_dir not in sys.path:
    sys.path.insert(0, script_dir)

# Add logic_auto_driving_COPY to path for legacy modules
# IMPORTANT: append (not insert) so the *local* control/ takes priority
_LOGIC_DIR = os.path.abspath(os.path.join(script_dir, '..', '..', 'logic_auto_driving_COPY'))
if _LOGIC_DIR not in sys.path:
    sys.path.append(_LOGIC_DIR)

# ---------------------------------------------------------------------------
# Project imports
# ---------------------------------------------------------------------------
from scenarios.roundabout import *            # Environment, carla
import control.vehicle_model as model
from control.trackingMPC import MPC_controller

# Frenet-frame lanelet geometry
from abstraction.roundabout_lanelets import RoundaboutLaneletMap

# Decoupled abstraction + helpers
from abstraction.roundabout_abstraction import (
    build_roundabout_abstraction,
    SysAbs1D,
    build_label_matrices,
)

# DFA tree risk-minimisation solver
from decision.specification.roundabout_dfa import RoundaboutDFA
from decision.maker_roundabout_dp import RoundaboutDPDecisionMaker


# ---------------------------------------------------------------------------
# MPC reference-trajectory builder
# ---------------------------------------------------------------------------

def build_mpc_reference(
    action_fn,
    rmap: RoundaboutLaneletMap,
    s0: float,
    d0: float,
    section: int,
    lane: int,
    mpc_dt: float,
    mpc_horizon: int,
    lane_width: float,
) -> np.ndarray:
    """
    Roll out the DP policy at MPC resolution and convert each
    Frenet waypoint to Cartesian.

    Parameters
    ----------
    action_fn : callable(s, d) -> (v_s, v_d)
        Policy query returning longitudinal and lateral speed.

    Returns
    -------
    ref : np.ndarray (4, mpc_horizon)
        Each column is [x, y, v, yaw].
    """
    ref = np.zeros((4, mpc_horizon), dtype=float)
    s, d = s0, d0
    sec = section

    for k in range(mpc_horizon):
        v_s, v_d = action_fn(s, d)

        s += v_s * mpc_dt
        d += v_d * mpc_dt

        # Handle section wrap
        sl = rmap.get_section_lanelet(sec, lane)
        while s >= sl.arc_length:
            s -= sl.arc_length
            sec = rmap.next_section(sec)
            sl = rmap.get_section_lanelet(sec, lane)
        while s < 0:
            sec = rmap.prev_section(sec)
            sl = rmap.get_section_lanelet(sec, lane)
            s += sl.arc_length

        # Convert to Cartesian — force d=0 so the reference stays on
        # the lane centre-line (the MPC steers to track this).
        cart = rmap.to_cartesian(sec, lane, s, 0.0)
        ref[0, k] = cart.x
        ref[1, k] = cart.y
        ref[2, k] = max(abs(v_s), 1.0)     # desired speed (≥1 m/s)
        ref[3, k] = cart.heading

    return ref


# ===========================================================================
# Main
# ===========================================================================

def main():
    argparser = argparse.ArgumentParser(description='Roundabout DP + MPC (single car)')
    argparser.add_argument('--host', metavar='H', default='127.0.0.1', help='IP of the host server')
    argparser.add_argument('-p', '--port', default=2000, type=int, help='TCP port to listen to')
    args = argparser.parse_args()
    running = True
    env = None

    # =====================================================================
    #  ROUNDABOUT CONFIGURATION
    # =====================================================================
    CENTRE        = (-0.5, 0.5)      # roundabout centre in CARLA world coords
    INNER_RADIUS  = 13.5             # [m]  inner edge of innermost ring
    LANE_WIDTH    = 4.0              # [m]
    N_LANES       = 4                # concentric rings
    N_SECTIONS    = 12               # angular sectors (30° each)
    DRIVE_LANE    = 2                # drivable lane (0 = island, 3 = outer boundary)
    DIRECTION     = "cw"             # CW in maths ⇒ CCW visually in CARLA

    # DP grid resolution
    N_S = 10                         # longitudinal cells per section
    N_D = 5                         # lateral cells per lane
    V_S_MAX = 10.0                   # max longitudinal speed [m/s]
    V_D_MAX = 2.0                    # max lateral speed [m/s]
    N_SPEED_S = 5                    # number of longitudinal speed actions
    N_SPEED_D = 5                    # number of lateral speed actions

    DT_DP  = 0.05                     # DP abstraction time step [s]
    GAMMA  = 0.95                    # discount factor

    # Cost-map tuning knobs
    K_SPEED       = 0.5              # reward scale for forward speed
    K_LAT         = 0.1              # penalty scale for lateral speed
    ROAD_REWARD   = -1.0             # negative cost → reward for being on road
    EDGE_PENALTY  = 50.0             # large positive cost at lane edges

    # DFA tree parameters
    N_TREE_ITERS  = 3                # outer iterations (grow + policy + VI)
    N_GROW        = 2                # tree expansions per outer iteration
    N_VI_PER_ITER = 10               # value-iteration sweeps per outer iteration

    try:
        # =================================================================
        #  1. ROUNDABOUT LANELET MAP  (Frenet-frame geometry)
        #     Created first so we can compute the correct spawn heading.
        # =================================================================
        rmap = RoundaboutLaneletMap(
            centre=CENTRE,
            inner_radius=INNER_RADIUS,
            lane_width=LANE_WIDTH,
            n_lanes=N_LANES,
            n_sections=N_SECTIONS,
            direction=DIRECTION,
        )
        print(rmap.summary())

        # Reference arc length for one section in DRIVE_LANE
        section_L = rmap.section_arc_length(DRIVE_LANE)
        print(f"Reference section arc length (lane {DRIVE_LANE}): {section_L:.2f} m")

        # Compute spawn pose from the lanelet map
        # Use _identify_section to find what section the original spawn
        # point falls into under the current direction convention.
        _orig_spawn = np.array([-2.1, 20.2])
        start_section = rmap._identify_section(_orig_spawn)
        cart_start = rmap.to_cartesian(start_section, DRIVE_LANE,
                                        0.5 * section_L, 0.0)
        ego_sp = carla.Transform(
            carla.Location(x=cart_start.x, y=cart_start.y, z=0.3),
            carla.Rotation(yaw=math.degrees(cart_start.heading)),
        )
        print(f"Spawn: section={start_section}, "
              f"x={cart_start.x:.2f}, y={cart_start.y:.2f}, "
              f"heading={cart_start.heading:.3f} rad "
              f"({math.degrees(cart_start.heading):.1f}°)")

        # =================================================================
        #  2. CARLA ENVIRONMENT  (spawn ego car with correct heading)
        # =================================================================
        env = Environment(args, ego_transform=ego_sp)
        env.world.tick()

        spectator = env.world.get_spectator()
        spectator.set_transform(
            carla.Transform(carla.Location(z=50), carla.Rotation(pitch=-90))
        )

        origin = carla.Location(x=CENTRE[0], y=CENTRE[1], z=0.2)

        # =================================================================
        #  3. VEHICLE MODEL + MPC CONTROLLER
        # =================================================================
        car_model = model.Vehicle(env.ego_car, env.dt, origin)
        ego_controller = MPC_controller(car_model)

        MPC_DT      = ego_controller.dt        # 0.1 s
        MPC_HORIZON = ego_controller.horizon    # 10 steps

        # Draw lanelets in CARLA for visualisation
        rmap.draw_in_carla(env.world, z=0.2, life_time=120.0,
                           draw_s_grid=False, draw_section_labels=True)

        # =================================================================
        #  4. BUILD DECOUPLED ABSTRACTION  (transition matrices + costs)
        # =================================================================

        abs_data = build_roundabout_abstraction(
            section_arc_length=section_L,
            lane_width=LANE_WIDTH,
            dt=DT_DP,
            N_s=N_S,
            N_d=N_D,
            v_s_max=V_S_MAX,
            v_d_max=V_D_MAX,
            n_speed_levels_s=N_SPEED_S,
            n_speed_levels_d=N_SPEED_D,
            k_speed=K_SPEED,
            k_lat=K_LAT,
            road_reward=ROAD_REWARD,
            edge_penalty=EDGE_PENALTY,
        )

        # =================================================================
        #  5. DFA SPECIFICATION + TREE SOLVER
        # =================================================================
        dfa = RoundaboutDFA()
        print(dfa.summary())

        # Wrap transition matrices for DFATree compatibility
        sysAbs = [
            SysAbs1D(abs_data['P_s']),    # longitudinal
            SysAbs1D(abs_data['P_d']),    # lateral
        ]

        # Per-dimension label matrices  (n_letters × N)
        L_s, L_d = build_label_matrices(N_S, N_D, n_letters=dfa.n_letters,
                                         edge_cells=1)

        # Initial policy: None → DFATree starts with uniform
        n_dfa_states = dfa.n_states
        pol_init = np.empty((n_dfa_states, 2), dtype=object)
        for q in range(n_dfa_states):
            for d_idx in range(2):
                pol_init[q][d_idx] = None

        # Uniform initial state distribution per dimension
        rho = [
            np.ones(N_S, dtype=float) / N_S,
            np.ones(N_D, dtype=float) / N_D,
        ]

        # Cost maps for the tree (state costs from the abstraction)
        cost_map = [abs_data['state_cost_s'], abs_data['state_cost_d']]

        # Build and solve DFA tree
        maker = RoundaboutDPDecisionMaker(
            dfa=dfa,
            sysAbs=sysAbs,
            nx_list=[N_S, N_D],
            L=[L_s, L_d],
            pol=pol_init,
            rho=rho,
            cost_map=cost_map,
            centres_s=abs_data['centres_s'],
            centres_d=abs_data['centres_d'],
            acc_s=abs_data['acc_s'],
            acc_d=abs_data['acc_d'],
            n_tree_iters=N_TREE_ITERS,
            n_vi_per_iter=N_VI_PER_ITER,
            n_grow=N_GROW,
            gamma=GAMMA,
            action_cost=[abs_data['action_cost_s'],
                         abs_data['action_cost_d']],
        )

        # Convenience: create a simple (s, d) → (v_s, v_d) callable
        def dp_action(s: float, d: float):
            v_s, v_d, _ = maker.get_action(s, d, 0, DRIVE_LANE)
            return v_s, v_d

        # =================================================================
        #  6. MAIN SIMULATION LOOP
        # =================================================================
        print("\n========== Starting simulation loop ==========\n")
        step = 0

        while running:
            step += 1
            env.world.tick()
            car_model.update()

            # --- Ego world state ---
            ego_xy = np.array([car_model.x, car_model.y])
            ego_v  = car_model.v
            ego_yaw = car_model.yaw

            # --- Map to Frenet coordinates via lanelet map ---
            sec_id, lane_id, frenet = rmap.to_frenet(ego_xy, speed=ego_v, yaw=ego_yaw)
            s_ego = frenet.s
            d_ego = frenet.d

            # --- Query DP policy ---
            v_s, v_d = dp_action(s_ego, d_ego)

            # --- Build MPC reference trajectory ---
            ref_traj = build_mpc_reference(
                action_fn=dp_action,
                rmap=rmap,
                s0=s_ego, d0=d_ego,
                section=sec_id, lane=DRIVE_LANE,
                mpc_dt=MPC_DT,
                mpc_horizon=MPC_HORIZON,
                lane_width=LANE_WIDTH,
            )

            # --- MPC tracking ---
            try:
                control_cmd = ego_controller.solve_trajectory(ref_traj)
                env.ego_car.apply_control(control_cmd)
            except Exception as e:
                # Fallback: single-point tracking
                try:
                    target_point = (ref_traj[0, 0], ref_traj[1, 0], ref_traj[3, 0])
                    control_cmd = ego_controller.solve(target_point, max(v_s, 1.0))
                    env.ego_car.apply_control(control_cmd)
                except Exception as e2:
                    if step % 50 == 0:
                        print(f"[Step {step}] MPC Error: {e2}")
                    env.ego_car.apply_control(carla.VehicleControl(brake=0.0, throttle=0.3))

            # --- Periodic logging ---
            if step % 100 == 0:
                print(
                    f"[Step {step}] "
                    f"sec={sec_id}, lane={lane_id}, "
                    f"s={s_ego:.2f}, d={d_ego:.2f}, "
                    f"v_s={v_s:.1f}, v_d={v_d:.2f}, "
                    f"ego_v={ego_v:.1f} m/s"
                )

    finally:
        if env is not None:
            env.__del__()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('Exit by user')
